//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smart.monitor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int PontodeAtendimento {
            get {
                return ((int)(this["PontodeAtendimento"]));
            }
            set {
                this["PontodeAtendimento"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://anima.craos.net")]
        public string Webservice {
            get {
                return ((string)(this["Webservice"]));
            }
            set {
                this["Webservice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/ws/?cn=as&c=304")]
        public string WebserviceListaControladoras {
            get {
                return ((string)(this["WebserviceListaControladoras"]));
            }
            set {
                this["WebserviceListaControladoras"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public string WebservicePort {
            get {
                return ((string)(this["WebservicePort"]));
            }
            set {
                this["WebservicePort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AbrirMonitordePedestre {
            get {
                return ((bool)(this["AbrirMonitordePedestre"]));
            }
            set {
                this["AbrirMonitordePedestre"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AbrirMonitordeVeiculos {
            get {
                return ((bool)(this["AbrirMonitordeVeiculos"]));
            }
            set {
                this["AbrirMonitordeVeiculos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nenhuma controladora selecionada")]
        public string DescricaoControladoraSelecionada {
            get {
                return ((string)(this["DescricaoControladoraSelecionada"]));
            }
            set {
                this["DescricaoControladoraSelecionada"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int idControladoraSelecionada {
            get {
                return ((int)(this["idControladoraSelecionada"]));
            }
            set {
                this["idControladoraSelecionada"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IniciarConexaoAutomaticamente {
            get {
                return ((bool)(this["IniciarConexaoAutomaticamente"]));
            }
            set {
                this["IniciarConexaoAutomaticamente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PesquisarRegistrosnaBaseLocal {
            get {
                return ((bool)(this["PesquisarRegistrosnaBaseLocal"]));
            }
            set {
                this["PesquisarRegistrosnaBaseLocal"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Host=localhost;Username=postgres;Password=yu45thn@;Database=smart")]
        public string ConexaoLocalHost {
            get {
                return ((string)(this["ConexaoLocalHost"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5432")]
        public string ConexaoLocalPorta {
            get {
                return ((string)(this["ConexaoLocalPorta"]));
            }
            set {
                this["ConexaoLocalPorta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AbrirMonitordeOperacoes {
            get {
                return ((bool)(this["AbrirMonitordeOperacoes"]));
            }
            set {
                this["AbrirMonitordeOperacoes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExigirAutenticacaoAntesdeIniciar {
            get {
                return ((bool)(this["ExigirAutenticacaoAntesdeIniciar"]));
            }
            set {
                this["ExigirAutenticacaoAntesdeIniciar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://anima.craos.net/smart.auth/auth.html?system=smart.ctrl")]
        public string OrigemLogin {
            get {
                return ((string)(this["OrigemLogin"]));
            }
            set {
                this["OrigemLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AbrirPaineldeControleAutomaticos {
            get {
                return ((bool)(this["AbrirPaineldeControleAutomaticos"]));
            }
            set {
                this["AbrirPaineldeControleAutomaticos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public int Aparencia {
            get {
                return ((int)(this["Aparencia"]));
            }
            set {
                this["Aparencia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState MDIUserWindowsState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["MDIUserWindowsState"]));
            }
            set {
                this["MDIUserWindowsState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Manual")]
        public global::System.Windows.Forms.FormStartPosition UserWindowStartPosition {
            get {
                return ((global::System.Windows.Forms.FormStartPosition)(this["UserWindowStartPosition"]));
            }
            set {
                this["UserWindowStartPosition"] = value;
            }
        }
    }
}
